### ISSUE TITLE
レイアウト構成作成

### ISSUE THREAD

**Issue by terumi-s22** [villainsbbc/love#6]
## Overview
ヘッダーやフッターを含むレイアウトコンポーネントをどのように配置して各ページで表示させるか構成を決める。

## Purpose
レイアウトコンポーネントの開発を進めるため。

## Tasks

- [x] レイアウトコンポーネントに含めるコンテンツを洗い出す
  - 現状のヘッダー、フッターにいれているもの
  - ナビゲーションバーも含める？
- [x] Reactにおいて一般的なレイアウトコンポーネントの構成を調査
  - 正解はないかもなので、やりたいことと照らし合わせて考える
    - 各ページで現在のページがわかるように色分けしたいとか(これはナビゲーションバーをレイアウトコンポーネントも含めるならばだけど)、基本的には今のホームページでやっていることができればOK 
- [x] 構成の決定
  - 上記であげたコンテンツ(コンポーネント)をどうレイアウトコンポーネントに配置するか
  - レイアウトコンポーネントはどこに配置するか

## Outputs
- レイアウト構成図
  - ディレクトリ構成 
  - どのファイルにどのコンポーネントを配置するか(コンポーネントの親子関係も含む)
 

## Notices
issue作っててナビケーションバーはレイアウトコンポーネントに含めないほうがいいのではと思ってきたけど、たぶん好みとかも入ってくると思うし、一応調べたうえ理由込みで結論出してください。

**Comment by villainsbbc** [comment]
### レイアウトコンポーネントに含めるコンテンツを洗い出す
- ロゴ
- タイトル
- SNSリンク群
- コピーライト
- よくある質問/当サイトの取り扱いのリンク

![image](https://user-images.githubusercontent.com/88573804/231163988-d9dbf37b-4ac6-4896-9d92-1eb3cf82255b.png)

![image](https://user-images.githubusercontent.com/88573804/231325072-05a71250-1b72-4f71-b1b5-7012cb3f02bc.png)


※ナビゲーションバーは動的に変化する部分(今いるページの色が変わる)があるため，レイアウトコンポーネントに含めるべきではないと判断
⇒レイアウトコンポーネントは各ページで読み込ませたくない(というかそういうもの)というのも理由の一つ

**Comment by villainsbbc** [comment]
### Reactにおいて一般的なレイアウトコンポーネントの構成を調査
なんかあんまり一般的がなにか出てこない。。。
レイアウトコンポーネントをApp.jsに書いてる人もいればindex.jsに書いてる人もいる。
Routerの中に入れてる人もいた。
...
結果たぶんどこでもよさそう

参考
- https://j-hack.gitbooks.io/meteor-1-3-react-tutorial/content/step3.html
- https://yoheiko.com/blog/react%E3%81%A7%E8%A4%87%E6%95%B0%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E4%BD%9C%E3%82%8B%E6%96%B9%E6%B3%95/

**Comment by villainsbbc** [comment]
[###](url) 構成の決定

#### 作成コンポーネント(とりあえず共通のもののみ)
- `Layout.js`
  - `Header.js`
    - ロゴ、タイトル、SNSリンク群
  - `Footer.js`
    - コピーライト 
    - よくある質問/当サイトの取り扱いのリンク
- `Navbar.js`
  - ナビゲーションバー

(あれ、てか`js`じゃなくて`jsx`じゃない？明日確認しよ)
=> 初期のReactでは`jsx`でなくては動かなかったが、現在のReactでは`js`に省略可能。
参考: https://www.codebu.org/react/just-use-jsx/#2_Tailwindcss

#### ディレクトリ構成(コンポーネントの配置込みで)
<img width="282" alt="スクリーンショット 2023-04-12 10 38 41" src="https://user-images.githubusercontent.com/112700063/231325076-1d82b8c3-ac83-44b8-9fb3-5d2c615bd7eb.png">
参考: https://qiita.com/mwkiyo/items/9549207680e71833a654
