### ISSUE TITLE
Layoutコンポーネントの作成

### ISSUE THREAD

**Issue by terumi-s22** [villainsbbc/love#9]
## Overview
#6 で決めた`Layout.js`を作成する。

## Purpose
全ページで共通する内容 `header.js`と`footer.js` をコンポーネント化したしたものを `Layout.js` でレイアウト化するため。

## Tasks
- [x] 仮でコンポーネント化した `header.js`と`footer.js` を `Layout.js` でimportする。
- [x] `index.js` で `Layout.js` をimportする。

## Outputs
- [x] 全てのページで仮のフッターヘッダーが見えること。

## Related Issue/PR
#6

**Comment by villainsbbc** [comment]
子要素の出力、childrenの使い方
https://choippo.com/react-component-children/
https://ja.reactjs.org/docs/composition-vs-inheritance.html#containment
